// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdggz-GJKpEuGYVyAQNN_cLKihsOxZ9Lk',
    appId: '1:337061833886:web:f782d1547949a6d172df8f',
    messagingSenderId: '337061833886',
    projectId: 'crud-50e98',
    authDomain: 'crud-50e98.firebaseapp.com',
    storageBucket: 'crud-50e98.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqY41wMJ2RIy3YvTs-8fKWVSadSOChlM4',
    appId: '1:337061833886:android:02cc3374dc22b70c72df8f',
    messagingSenderId: '337061833886',
    projectId: 'crud-50e98',
    storageBucket: 'crud-50e98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPeIjbgs38dk_rpdjdzrt6W_CgzZBj-30',
    appId: '1:337061833886:ios:1e9cb65ab0d5958272df8f',
    messagingSenderId: '337061833886',
    projectId: 'crud-50e98',
    storageBucket: 'crud-50e98.appspot.com',
    iosBundleId: 'com.example.learningCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPeIjbgs38dk_rpdjdzrt6W_CgzZBj-30',
    appId: '1:337061833886:ios:8683df8b8b6252ec72df8f',
    messagingSenderId: '337061833886',
    projectId: 'crud-50e98',
    storageBucket: 'crud-50e98.appspot.com',
    iosBundleId: 'com.example.learningCrud.RunnerTests',
  );
}
